name: OpenSSF Scorecard

on:
  branch_protection_rule:
  push:
    branches: [ master, main ]
  schedule:
    - cron: "37 3 * * 2"

permissions:
  actions: read
  contents: read

jobs:
  scorecard:
    name: Scorecard
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      actions: read
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ossf/scorecard-action@v2.4.3
        with:
          results_file: scorecard.sarif
          results_format: sarif
          publish_results: true
